name: Slack Notify
description: "Send Slack notification"
inputs:
  webhook:
    description: "Slack Webhook URL"
    required: true
    type: string
  title:
    description: "Notification title"
    required: true
    type: string
  stage:
    description: "Notification stage (start, success, failure)"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Send Notification to Slack
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "${{ inputs.title }}",
          }