name: Slack Notify
description: "Send Slack notification"
inputs:
  webhook:
    description: "Slack Webhook URL"
    required: true
    type: string
  title:
    description: "Notification title"
    required: true
    type: string
  stage:
    description: "Notification stage (start, success, failure)"
    required: false
    type: string
  notes:
    description: "Release notes to include in the notification"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Send Notification to Slack
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook: ${{ inputs.webhook }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "${{ inputs.title }}",
            "attachments": [
              {
                "color": "${{ inputs.stage == 'success' && '#36a64f' || inputs.stage == 'failure' && '#ff0000' || '#cccccc' }}",
                "fields": [
                  {
                    "title": "Build Status",
                    "value": "${{ inputs.stage == 'success' && 'Success :white_check_mark:' || inputs.stage == 'failure' && 'Failed :x:' || 'In Progress :hourglass_flowing_sand:' }}",
                    "short": false
                  }
                  ${{ inputs.notes && ',{
                    "title": "Release Notes",
                    "value": "```' }}${{ inputs.notes }}${{ inputs.notes && '```",
                    "short": false
                  }' }}
                ]
              }
            ]
          }
