name: GitHub Actions Demo # Workflow name
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 #Run workflow name
on: #trigger
  push:
    branches:
      - main
jobs: 
  Explore-GitHub-Actions:
    name: Build & Release 
    runs-on: macos-latest 
    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
      #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get