name: GitHub Actions Demo # Workflow name
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 #Run workflow name
on: #trigger
  push:
    branches:
      - development
jobs: 
  setup:
    name: Build & Deploy
    runs-on: macos-latest
    steps:
      #1 Checkout Repository
      - name: Checkout Repository #checkout action to check out (or clone) the repository code into the workflow environment.
        uses: actions/checkout@v4
      #2 Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "zulu"
      #3 Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3
      - name: Install Dependencies
        run: |
          flutter --version
          flutter pub get
      - name: Load environment
        run: |
          echo "APP_ANME=${{secrets.APP_ANME}}" > .env
      - name: Generate env
        run: flutter pub run build_runner build --delete-conflicting-outputs
      #4 Build APK (Android)
      - name: Build APK (android)
        run: flutter build apk --release