name: GitHub Actions Demo # Workflow name
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 #Run workflow name
on: #trigger
  push:
    branches:
      - main
jobs: 
  setup:
    name: Setup environment
    runs-on: macos-latest
    steps:
      #1 Checkout Repository
      - name: Checkout Repository #checkout action to check out (or clone) the repository code into the workflow environment.
        uses: actions/checkout@v4
      #2 Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "zulu"
      #3 Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3
  dependencies:
    name: Install Dependencies
    runs-on: macos-latest
    steps:
      - name: Flutter version
        run: flutter pub get
      - name: Dependencies
        run: flutter pub get